micronaut:
  application:
    name: demo

endpoints:
  health:
    enabled: true
  env:
    enabled: true
    sensitive: false

hermes:
  management:
    enabled: true
    url: ${HERMES_MANAGEMENT_URL}
    topics:
      - name: ${EVENTS_TOPIC_NAME}
        subscription:
          name: test-app
          endpoint: http://my-endpoint
          secret: ${EVENTS_SUBSCRIPTION_SECRET}
          policy:
            rate: 400
            message-ttl: 3600
            message-backoff: 1000
            retry-client-errors: false
            request-timeout: 1000
            socket-timeout: 500
            inflight-size: 100
            backoff-multiplier: 1
            backoff-max-interval-in-sec: 600
          owner:
            source: Plaintext
            id: app-owner
